import { describe, expect, it } from "vitest";
import * as browserExtensionCore from "../src/index.js";
import {
  BackgroundRouter,
  BackgroundInspectCoordinator,
  BrowserBridgeClient,
  BrowserWindowLinkStore,
  ContentInspectLease,
  createPanelIcons,
  createBackgroundRouter,
  createDevtoolsPanelPortName,
  createInspectPayload,
  createDefaultTabRefreshState,
  captureTopScrollSnapshot,
  DOM_PROTOCOL_MAX_ANCESTOR_PATH_LENGTH,
  DOM_PROTOCOL_MAX_CHILDREN_PAGE_LENGTH,
  DOM_PROTOCOL_MAX_IDENTIFIER_LENGTH,
  DOM_PROTOCOL_MAX_INVALIDATION_BRANCHES,
  DOM_PROTOCOL_MAX_LABEL_LENGTH,
  DOM_PROTOCOL_MAX_SERIALIZED_MESSAGE_BYTES,
  DOM_PROTOCOL_MAX_SUMMARY_LENGTH,
  DomNodeRegistry,
  DomPanelView,
  DomTreeController,
  DomTreeRecoveryCoordinator,
  DomTreeProvider,
  DomTreeProviderError,
  DomTreeView,
  DomProtocolError,
  FrameRegistry,
  InspectMode,
  PAGE_INSPECTION_SELECTION_INTERVAL_MS,
  PageInspectionSession,
  PageOverlay,
  PanelController,
  PanelSettingsController,
  ResolutionPresenter,
  SourceNavigationController,
  SourcePaneController,
  formatResolutionFooter,
  presentResolution,
  PanelInspectTransport,
  parseLinkCode,
  parseDomEvent,
  parseDomRequest,
  parseDomResponse,
  parsePanelTabSettingsCommand,
  parseContentRefreshCommand,
  refreshExternalStylesheets,
  restoreTopScrollSnapshot,
  parseTabRefreshState,
  registerDevtoolsPanel,
  sanitizeErrorMessage,
  startBackgroundRuntime,
  startContentScriptRuntime,
  startContentRefreshRuntime,
  startDevtoolsRuntime,
  startPanelRuntime,
  TabRefreshCoordinator,
  TabRefreshStateStore,
  TopScrollSnapshotLeaseStore,
  virtualTreeRows,
  WindowConnectionCoordinator,
} from "../src/index.js";

describe("browser extension core exports", () => {
  it("exports transport, inspection, and DevTools runtimes", () => {
    const publicExports = browserExtensionCore as unknown as Record<
      string,
      unknown
    >;
    expect(BrowserBridgeClient).toBeTypeOf("function");
    expect(BackgroundInspectCoordinator).toBeTypeOf("function");
    expect(BackgroundRouter).toBeTypeOf("function");
    expect(BrowserWindowLinkStore).toBeTypeOf("function");
    expect(ContentInspectLease).toBeTypeOf("function");
    expect(createBackgroundRouter).toBeTypeOf("function");
    expect(createDevtoolsPanelPortName).toBeTypeOf("function");
    expect(createInspectPayload).toBeTypeOf("function");
    expect(createDefaultTabRefreshState).toBeTypeOf("function");
    expect(captureTopScrollSnapshot).toBeTypeOf("function");
    expect(DOM_PROTOCOL_MAX_ANCESTOR_PATH_LENGTH).toBe(64);
    expect(DOM_PROTOCOL_MAX_CHILDREN_PAGE_LENGTH).toBe(100);
    expect(DOM_PROTOCOL_MAX_IDENTIFIER_LENGTH).toBe(128);
    expect(DOM_PROTOCOL_MAX_INVALIDATION_BRANCHES).toBe(128);
    expect(DOM_PROTOCOL_MAX_LABEL_LENGTH).toBe(512);
    expect(DOM_PROTOCOL_MAX_SERIALIZED_MESSAGE_BYTES).toBe(64 * 1024);
    expect(DOM_PROTOCOL_MAX_SUMMARY_LENGTH).toBe(512);
    expect(publicExports.DOM_STABLE_LOCATOR_VERSION).toBe(1);
    expect(publicExports.DOM_STABLE_LOCATOR_MAX_DEPTH).toBe(64);
    expect(publicExports.DOM_STABLE_LOCATOR_MAX_BOUNDARIES).toBe(16);
    expect(publicExports.DOM_STABLE_LOCATOR_MAX_CLASSES).toBe(8);
    expect(publicExports.DOM_STABLE_LOCATOR_MAX_ATTRIBUTES).toBe(8);
    expect(publicExports.DOM_STABLE_LOCATOR_MAX_TOKEN_LENGTH).toBe(128);
    expect(publicExports.DOM_TREE_RECOVERY_MAX_EXPANDED).toBe(64);
    expect(publicExports.locatorDepth).toBeTypeOf("function");
    expect(DomNodeRegistry).toBeTypeOf("function");
    expect(DomPanelView).toBeTypeOf("function");
    expect(DomTreeController).toBeTypeOf("function");
    expect(DomTreeRecoveryCoordinator).toBeTypeOf("function");
    expect(DomTreeProvider).toBeTypeOf("function");
    expect(DomTreeProviderError).toBeTypeOf("function");
    expect(DomTreeView).toBeTypeOf("function");
    expect(DomProtocolError).toBeTypeOf("function");
    expect(FrameRegistry).toBeTypeOf("function");
    expect(createPanelIcons).toBeTypeOf("function");
    expect(InspectMode).toBeTypeOf("function");
    expect(PAGE_INSPECTION_SELECTION_INTERVAL_MS).toBe(100);
    expect(PageInspectionSession).toBeTypeOf("function");
    expect(PageOverlay).toBeTypeOf("function");
    expect(parseLinkCode).toBeTypeOf("function");
    expect(parseDomEvent).toBeTypeOf("function");
    expect(parseDomRequest).toBeTypeOf("function");
    expect(parseDomResponse).toBeTypeOf("function");
    expect(parsePanelTabSettingsCommand).toBeTypeOf("function");
    expect(parseContentRefreshCommand).toBeTypeOf("function");
    expect(refreshExternalStylesheets).toBeTypeOf("function");
    expect(restoreTopScrollSnapshot).toBeTypeOf("function");
    expect(parseTabRefreshState).toBeTypeOf("function");
    expect(PanelController).toBeTypeOf("function");
    expect(PanelSettingsController).toBeTypeOf("function");
    expect(ResolutionPresenter).toBeTypeOf("function");
    expect(SourceNavigationController).toBeTypeOf("function");
    expect(SourcePaneController).toBeTypeOf("function");
    expect(formatResolutionFooter).toBeTypeOf("function");
    expect(presentResolution).toBeTypeOf("function");
    expect(PanelInspectTransport).toBeTypeOf("function");
    expect(registerDevtoolsPanel).toBeTypeOf("function");
    expect(sanitizeErrorMessage).toBeTypeOf("function");
    expect(startBackgroundRuntime).toBeTypeOf("function");
    expect(startContentScriptRuntime).toBeTypeOf("function");
    expect(startContentRefreshRuntime).toBeTypeOf("function");
    expect(startDevtoolsRuntime).toBeTypeOf("function");
    expect(startPanelRuntime).toBeTypeOf("function");
    expect(TabRefreshCoordinator).toBeTypeOf("function");
    expect(TabRefreshStateStore).toBeTypeOf("function");
    expect(TopScrollSnapshotLeaseStore).toBeTypeOf("function");
    expect(virtualTreeRows).toBeTypeOf("function");
    expect(WindowConnectionCoordinator).toBeTypeOf("function");
  });
});
